name: Trigger auto deployment for container-app-243sgkdgo7umg

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-243sgkdgo7umg-AutoDeployTrigger-5fc7481a-fc5c-4e1f-a7a2-244539289658.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP243SGKDGO7UMG_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP243SGKDGO7UMG_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP243SGKDGO7UMG_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: containerreg243sgkdgo7umg.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPP243SGKDGO7UMG_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP243SGKDGO7UMG_REGISTRY_PASSWORD }}
          containerAppName: container-app-243sgkdgo7umg
          resourceGroup: ResourceGroup1
          imageToBuild: containerreg243sgkdgo7umg.azurecr.io/container-app-243sgkdgo7umg:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


