name: Trigger auto deployment for container-app-zvv4kvjlanmz2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-zvv4kvjlanmz2-AutoDeployTrigger-2c81a512-aa29-4feb-9924-a3e633c9ba93.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZVV4KVJLANMZ2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZVV4KVJLANMZ2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZVV4KVJLANMZ2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: containerregzvv4kvjlanmz2.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPZVV4KVJLANMZ2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZVV4KVJLANMZ2_REGISTRY_PASSWORD }}
          containerAppName: container-app-zvv4kvjlanmz2
          resourceGroup: ResourceGroup1
          imageToBuild: containerregzvv4kvjlanmz2.azurecr.io/container-app-zvv4kvjlanmz2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


