name: Trigger auto deployment for container-app-qmkt4ptdizfjm

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-qmkt4ptdizfjm-AutoDeployTrigger-459ef791-626f-4057-aacd-b1621adb70c4.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPQMKT4PTDIZFJM_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPQMKT4PTDIZFJM_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPQMKT4PTDIZFJM_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: containerregqmkt4ptdizfjm.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPQMKT4PTDIZFJM_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPQMKT4PTDIZFJM_REGISTRY_PASSWORD }}
          containerAppName: container-app-qmkt4ptdizfjm
          resourceGroup: ResourceGroup1
          imageToBuild: containerregqmkt4ptdizfjm.azurecr.io/container-app-qmkt4ptdizfjm:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


